version: "3.3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=flask_app
      - MYSQL_USER=flask_user
      - MYSQL_PASSWORD=flask_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always

  flask-app:
    container_name: flask-app
    image: reedonly/flask-app:latest
    build: .
    depends_on:
      - mysql
    environment:
      - FLASK_APP=/opt/flask_app/flask_app/__init__.py
      - FLASK_DEBUG=1
    ports:
      - 5000:5000
    volumes:
      - ./config/.my.cnf:/home/flaskuser/.my.cnf
      - .:/opt/flask_app
    user: flaskuser
    command: bash -c "./wait_for_mysql.sh && flask db upgrade && flask run --host=0.0.0.0"
