#!/bin/bash
#
# Build a flask-app docker environment, start it, and enter a bash session on flask-app
#
# Usage:
#  ./launch

if [ "$(docker ps -q -f name=flask-app)" ]; then
    docker stop flask-app
fi

docker-compose up --build -d

docker exec -ti flask-app bash
